// <auto-generated />
using System;
using LaytonTemple.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LaytonTemple.Migrations
{
    [DbContext(typeof(DatetimeDBcontext))]
    [Migration("20220323202750_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("LaytonTemple.Models.Times", b =>
                {
                    b.Property<int>("TimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timeslot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TimeId");

                    b.ToTable("timeslots");

                    b.HasData(
                        new
                        {
                            TimeId = 1,
                            Available = true,
                            Timeslot = "03/23/2022 8 A.M."
                        },
                        new
                        {
                            TimeId = 2,
                            Available = true,
                            Timeslot = "03/23/2022 9 A.M."
                        },
                        new
                        {
                            TimeId = 3,
                            Available = true,
                            Timeslot = "03/23/2022 10 A.M."
                        },
                        new
                        {
                            TimeId = 4,
                            Available = true,
                            Timeslot = "03/23/2022 11 A.M."
                        },
                        new
                        {
                            TimeId = 5,
                            Available = true,
                            Timeslot = "03/23/2022 12 P.M."
                        },
                        new
                        {
                            TimeId = 6,
                            Available = true,
                            Timeslot = "03/23/2022 1 P.M."
                        },
                        new
                        {
                            TimeId = 7,
                            Available = true,
                            Timeslot = "03/23/2022 2 P.M."
                        },
                        new
                        {
                            TimeId = 8,
                            Available = true,
                            Timeslot = "03/23/2022 3 P.M."
                        },
                        new
                        {
                            TimeId = 9,
                            Available = true,
                            Timeslot = "03/23/2022 4 P.M."
                        },
                        new
                        {
                            TimeId = 10,
                            Available = true,
                            Timeslot = "03/23/2022 5 P.M."
                        },
                        new
                        {
                            TimeId = 11,
                            Available = true,
                            Timeslot = "03/23/2022 6 P.M."
                        },
                        new
                        {
                            TimeId = 12,
                            Available = true,
                            Timeslot = "03/23/2022 7 P.M."
                        },
                        new
                        {
                            TimeId = 13,
                            Available = true,
                            Timeslot = "03/23/2022 8 P.M."
                        },
                        new
                        {
                            TimeId = 14,
                            Available = true,
                            Timeslot = "03/24/2022 8 A.M."
                        },
                        new
                        {
                            TimeId = 15,
                            Available = true,
                            Timeslot = "03/24/2022 9 A.M."
                        },
                        new
                        {
                            TimeId = 16,
                            Available = true,
                            Timeslot = "03/24/2022 10 A.M."
                        },
                        new
                        {
                            TimeId = 17,
                            Available = true,
                            Timeslot = "03/24/2022 11 A.M."
                        },
                        new
                        {
                            TimeId = 18,
                            Available = true,
                            Timeslot = "03/24/2022 12 P.M."
                        },
                        new
                        {
                            TimeId = 19,
                            Available = true,
                            Timeslot = "03/24/2022 1 P.M."
                        },
                        new
                        {
                            TimeId = 20,
                            Available = true,
                            Timeslot = "03/24/2022 2 P.M."
                        },
                        new
                        {
                            TimeId = 21,
                            Available = true,
                            Timeslot = "03/24/2022 3 P.M."
                        },
                        new
                        {
                            TimeId = 22,
                            Available = true,
                            Timeslot = "03/24/2022 4 P.M."
                        },
                        new
                        {
                            TimeId = 23,
                            Available = true,
                            Timeslot = "03/24/2022 5 P.M."
                        },
                        new
                        {
                            TimeId = 24,
                            Available = true,
                            Timeslot = "03/24/2022 6 P.M."
                        },
                        new
                        {
                            TimeId = 25,
                            Available = true,
                            Timeslot = "03/24/2022 7 P.M."
                        },
                        new
                        {
                            TimeId = 26,
                            Available = true,
                            Timeslot = "03/24/2022 8 P.M."
                        },
                        new
                        {
                            TimeId = 27,
                            Available = true,
                            Timeslot = "03/25/2022 8 A.M."
                        },
                        new
                        {
                            TimeId = 28,
                            Available = true,
                            Timeslot = "03/25/2022 9 A.M."
                        },
                        new
                        {
                            TimeId = 29,
                            Available = true,
                            Timeslot = "03/25/2022 10 A.M."
                        },
                        new
                        {
                            TimeId = 30,
                            Available = true,
                            Timeslot = "03/25/2022 11 A.M."
                        },
                        new
                        {
                            TimeId = 31,
                            Available = true,
                            Timeslot = "03/25/2022 12 P.M."
                        },
                        new
                        {
                            TimeId = 32,
                            Available = true,
                            Timeslot = "03/25/2022 1 P.M."
                        },
                        new
                        {
                            TimeId = 33,
                            Available = true,
                            Timeslot = "03/25/2022 2 P.M."
                        },
                        new
                        {
                            TimeId = 34,
                            Available = true,
                            Timeslot = "03/25/2022 3 P.M."
                        },
                        new
                        {
                            TimeId = 35,
                            Available = true,
                            Timeslot = "03/25/2022 4 P.M."
                        },
                        new
                        {
                            TimeId = 36,
                            Available = true,
                            Timeslot = "03/25/2022 5 P.M."
                        },
                        new
                        {
                            TimeId = 37,
                            Available = true,
                            Timeslot = "03/25/2022 6 P.M."
                        },
                        new
                        {
                            TimeId = 38,
                            Available = true,
                            Timeslot = "03/25/2022 7 P.M."
                        },
                        new
                        {
                            TimeId = 39,
                            Available = true,
                            Timeslot = "03/25/2022 8 P.M."
                        },
                        new
                        {
                            TimeId = 40,
                            Available = true,
                            Timeslot = "03/26/2022 8 A.M."
                        },
                        new
                        {
                            TimeId = 41,
                            Available = true,
                            Timeslot = "03/26/2022 9 A.M."
                        },
                        new
                        {
                            TimeId = 42,
                            Available = true,
                            Timeslot = "03/26/2022 10 A.M."
                        },
                        new
                        {
                            TimeId = 43,
                            Available = true,
                            Timeslot = "03/26/2022 11 A.M."
                        },
                        new
                        {
                            TimeId = 44,
                            Available = true,
                            Timeslot = "03/26/2022 12 P.M."
                        },
                        new
                        {
                            TimeId = 45,
                            Available = true,
                            Timeslot = "03/26/2022 1 P.M."
                        },
                        new
                        {
                            TimeId = 46,
                            Available = true,
                            Timeslot = "03/26/2022 2 P.M."
                        },
                        new
                        {
                            TimeId = 47,
                            Available = true,
                            Timeslot = "03/26/2022 3 P.M."
                        },
                        new
                        {
                            TimeId = 48,
                            Available = true,
                            Timeslot = "03/26/2022 4 P.M."
                        },
                        new
                        {
                            TimeId = 49,
                            Available = true,
                            Timeslot = "03/26/2022 5 P.M."
                        },
                        new
                        {
                            TimeId = 50,
                            Available = true,
                            Timeslot = "03/26/2022 6 P.M."
                        },
                        new
                        {
                            TimeId = 51,
                            Available = true,
                            Timeslot = "03/26/2022 7 P.M."
                        },
                        new
                        {
                            TimeId = 52,
                            Available = true,
                            Timeslot = "03/26/2022 8 P.M."
                        },
                        new
                        {
                            TimeId = 53,
                            Available = true,
                            Timeslot = "03/27/2022 8 A.M."
                        },
                        new
                        {
                            TimeId = 54,
                            Available = true,
                            Timeslot = "03/27/2022 9 A.M."
                        },
                        new
                        {
                            TimeId = 55,
                            Available = true,
                            Timeslot = "03/27/2022 10 A.M."
                        },
                        new
                        {
                            TimeId = 56,
                            Available = true,
                            Timeslot = "03/27/2022 11 A.M."
                        },
                        new
                        {
                            TimeId = 57,
                            Available = true,
                            Timeslot = "03/27/2022 12 P.M."
                        },
                        new
                        {
                            TimeId = 58,
                            Available = true,
                            Timeslot = "03/27/2022 1 P.M."
                        },
                        new
                        {
                            TimeId = 59,
                            Available = true,
                            Timeslot = "03/27/2022 2 P.M."
                        },
                        new
                        {
                            TimeId = 60,
                            Available = true,
                            Timeslot = "03/27/2022 3 P.M."
                        },
                        new
                        {
                            TimeId = 61,
                            Available = true,
                            Timeslot = "03/27/2022 4 P.M."
                        },
                        new
                        {
                            TimeId = 62,
                            Available = true,
                            Timeslot = "03/27/2022 5 P.M."
                        },
                        new
                        {
                            TimeId = 63,
                            Available = true,
                            Timeslot = "03/27/2022 6 P.M."
                        },
                        new
                        {
                            TimeId = 64,
                            Available = true,
                            Timeslot = "03/27/2022 7 P.M."
                        },
                        new
                        {
                            TimeId = 65,
                            Available = true,
                            Timeslot = "03/27/2022 8 P.M."
                        },
                        new
                        {
                            TimeId = 66,
                            Available = true,
                            Timeslot = "03/28/2022 8 A.M."
                        },
                        new
                        {
                            TimeId = 67,
                            Available = true,
                            Timeslot = "03/28/2022 9 A.M."
                        },
                        new
                        {
                            TimeId = 68,
                            Available = true,
                            Timeslot = "03/28/2022 10 A.M."
                        },
                        new
                        {
                            TimeId = 69,
                            Available = true,
                            Timeslot = "03/28/2022 11 A.M."
                        },
                        new
                        {
                            TimeId = 70,
                            Available = true,
                            Timeslot = "03/28/2022 12 P.M."
                        },
                        new
                        {
                            TimeId = 71,
                            Available = true,
                            Timeslot = "03/28/2022 1 P.M."
                        },
                        new
                        {
                            TimeId = 72,
                            Available = true,
                            Timeslot = "03/28/2022 2 P.M."
                        },
                        new
                        {
                            TimeId = 73,
                            Available = true,
                            Timeslot = "03/28/2022 3 P.M."
                        },
                        new
                        {
                            TimeId = 74,
                            Available = true,
                            Timeslot = "03/28/2022 4 P.M."
                        },
                        new
                        {
                            TimeId = 75,
                            Available = true,
                            Timeslot = "03/28/2022 5 P.M."
                        },
                        new
                        {
                            TimeId = 76,
                            Available = true,
                            Timeslot = "03/28/2022 6 P.M."
                        },
                        new
                        {
                            TimeId = 77,
                            Available = true,
                            Timeslot = "03/28/2022 7 P.M."
                        },
                        new
                        {
                            TimeId = 78,
                            Available = true,
                            Timeslot = "03/28/2022 8 P.M."
                        },
                        new
                        {
                            TimeId = 79,
                            Available = true,
                            Timeslot = "03/29/2022 8 A.M."
                        },
                        new
                        {
                            TimeId = 80,
                            Available = true,
                            Timeslot = "03/29/2022 9 A.M."
                        },
                        new
                        {
                            TimeId = 81,
                            Available = true,
                            Timeslot = "03/29/2022 10 A.M."
                        },
                        new
                        {
                            TimeId = 82,
                            Available = true,
                            Timeslot = "03/29/2022 11 A.M."
                        },
                        new
                        {
                            TimeId = 83,
                            Available = true,
                            Timeslot = "03/29/2022 12 P.M."
                        },
                        new
                        {
                            TimeId = 84,
                            Available = true,
                            Timeslot = "03/29/2022 1 P.M."
                        },
                        new
                        {
                            TimeId = 85,
                            Available = true,
                            Timeslot = "03/29/2022 2 P.M."
                        },
                        new
                        {
                            TimeId = 86,
                            Available = true,
                            Timeslot = "03/29/2022 3 P.M."
                        },
                        new
                        {
                            TimeId = 87,
                            Available = true,
                            Timeslot = "03/29/2022 4 P.M."
                        },
                        new
                        {
                            TimeId = 88,
                            Available = true,
                            Timeslot = "03/29/2022 5 P.M."
                        },
                        new
                        {
                            TimeId = 89,
                            Available = true,
                            Timeslot = "03/29/2022 6 P.M."
                        },
                        new
                        {
                            TimeId = 90,
                            Available = true,
                            Timeslot = "03/29/2022 7 P.M."
                        },
                        new
                        {
                            TimeId = 91,
                            Available = true,
                            Timeslot = "03/29/2022 8 P.M."
                        });
                });

            modelBuilder.Entity("LaytonTemple.Models.TourGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("Phone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timeslot")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId");

                    b.ToTable("TourGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
